steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - gcr.io/${_TARGET_PROJECT}/${_IMAGE}:${SHORT_SHA}
    - -t
    - gcr.io/${_TARGET_PROJECT}/${_IMAGE}:latest
    - -f
    - backend/Dockerfile
    - backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - gcr.io/${_TARGET_PROJECT}/${_IMAGE}:${SHORT_SHA}
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - gcr.io/${_TARGET_PROJECT}/${_IMAGE}:latest

images:
- gcr.io/${_TARGET_PROJECT}/${_IMAGE}:${SHORT_SHA}
- gcr.io/${_TARGET_PROJECT}/${_IMAGE}:latest

substitutions:
  _IMAGE: "escritores-backend"
  _REGION: "europe-west1"
  _TARGET_PROJECT: "escritores-nogueira"
  _REGISTRY: "europe-west1-docker.pkg.dev/escritores-nogueira/cloud-run-source-deploy"

timeout: "1200s"