#!/bin/sh                                                                                                                                                                                                                                                                                                              │set -x                                                                                                                                                                                                                                                                                                                 │
                                                                                                                                                                                                                                                                                                                       │
echo "Entrypoint script started"                                                                                                                                                                                                                                                                                       │
                                                                                                                                                                                                                                                                                                                        │
echo "Listing contents of /secrets"                                                                                                                                                                                                                                                                                    │
ls -la /secrets                                                                                                                                                                                                                                                                                                        │
                                                                                                                                                                                                                                                                                                                       │
echo "Contents of /secrets/.env:"                                                                                                                                                                                                                                                                                      │
cat /secrets/.env                                                                                                                                                                                                                                                                                                      │
                                                                                                                                                                                                                                                                                                                       │
echo "Attempting to start Java application"                                                                                                                                                                                                                                                                            │
  java -jar /opt/app/app.jar  
